name: emseq
channels:
  - conda-forge
  - bioconda

dependencies:
  - fastp
  - samtools
  - bioconductor-genomeinfodbdata=1.2.7
  - biscuit=1.6.0.20241216=*_1
  - dupsifter=1.3.0.20241113=*_1
  - bwa
  - bwameth
  - methyldackel
  - mosdepth
