name: emseq-ci
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - samtools=1.20
  - htslib=1.20
  - tabix  # provided via htslib, but fine to keep
  - fastp
  - fastqc
  - pigz
  - wget
