name: emseq
channels:
  - conda-forge
  - bioconda

dependencies:
  - fastp
  - fastqc
  - bedtools
  - samtools
  - bioconductor-genomeinfodbdata=1.2.7
  - bismark
  - bwa
  - bwameth
  - methyldackel
  - mosdepth
  - multiqc
  - r-argparse
  - r-data.table
  - r-ggplot2
  - r-cairo
  - r-scales
  - r-patchwork
  - r-matrixstats
  - biscuit=1.7.1.20250908
  - dupsifter=1.3.0.20241113
  - libdeflate=1.22
  - bedtools
