name: mosdepth
channels:
  - conda-forge
  - bioconda

dependencies:
  - samtools
  - bioconductor-genomeinfodbdata=1.2.7
  - mosdepth
  - r-argparse
  - r-data.table
  - r-ggplot2
  - r-cairo
  - jpeg
  - r-scales
  - r-patchwork
  - r-matrixstats
  - r-r.utils
