# -----------------------------
# Global runtime/config knobs
# -----------------------------
available-concurrency: 50
threads: 24
main-data-dir: "tests/full"
mosdepth-quant-levels: "1,5"

# -----------------------------
# Environments and repositories
# -----------------------------
envs:
  emseq: "config/emseq-conda-env.yaml"
  methylkit: "config/methylkit-conda-env.yaml"

repos:
  emseq: "./"

# -----------------------------
# Sample set and region filters
# -----------------------------
library-ids: ["lib001", "lib002", "lib003", "lib004"]
keep-bed: "tests/full/inputs/chr22.keep.bed"
exclude-bed: "tests/full/inputs/chr22.exclude.blacklist.bed.gz"

# -----------------------------
# Reference assemblies (primary + spike)
# -----------------------------
emseq_ref_assemblies:
  chr22:
    url: https:/ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz
    name: chr22
    input: chr22.test.fa.gz
  unmeth_lambda:
    url: https://www.neb.com/en-us/-/media/nebus/page-images/tools-and-resources/interactive-tools/dna-sequences-and-maps/text-documents/lambdafsa.txt?rev=c0c6669b9bd340ddb674ebfd9d55c691&hash=7E6375924CFF9457D0157D0D87C9AC19
    name: unmeth_lambda
    input: lambda.fa.gz
  puc19:
    url: https://www.neb.com/en-us/-/media/nebus/page-images/tools-and-resources/interactive-tools/dna-sequences-and-maps/text-documents/puc19fsa.txt?rev=6e10f4c4a4234d638e401cd2f4578ef0&hash=E71970068EEA191C175B3458DB99D7BB
    name: puc19
    input: pUC19.fa.gz

# -----------------------------
# Experiments (differential methylation experiments for methylKit;
# i.e., groupings/contrasts used to build methylBase/methylDiff)
# -----------------------------
meth-map:
  test:
    libs:        ["lib001","lib003","lib003","lib004"]
    emseq_ref_name:    ["chr22"]
    align_method: bwa_meth
    tx:          [0,0,1,1]
    mincov:      10
    mingroup:    1
    chunksize:   "1e9"
    win_size:    10000
