name: ci-snakemake

on:
  pull_request:
    paths:
      - "workflows/**"
      - "config/**"
      - "scripts/**"
      - ".github/workflows/ci-snakemake.yml"
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch: {}

concurrency:
  group: ci-snakemake-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      # Install micromamba for fast, reliable environment management
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: config/emseq-conda-env.yaml
          environment-name: emseq
          cache-environment: true

      - name: Verify required files
        run: |
          set -euo pipefail
          test -f config/emseq-conda-env.yaml
          test -f workflows/test.smk
          test -f config/test.yaml

      - name: Show environment info
        run: |
          micromamba info
          micromamba list -n emseq
          micromamba run -n emseq python -V
          micromamba run -n emseq snakemake --version
          micromamba run -n emseq samtools --version || true

      - name: Snakemake dry-run
        run: |
          micromamba run -n emseq snakemake \
          -s workflows/test.smk \
          --configfile config/test.yaml \
          --cores 4 \
          --dry-run \
          --printshellcmds \
          --rerun-incomplete \
          --resources concurrency=50

      - name: Summary
        if: always()
        run: |
          micromamba run -n emseq snakemake \
            -s workflows/test.smk --summary --cores 1 --dry-run
