name: ci-snakemake

on:
  pull_request:
    paths:
      - "workflows/**"
      - "config/**"
      - "scripts/**"
      - ".github/workflows/ci-snakemake.yml"
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch: {}

concurrency:
  group: ci-snakemake-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash -l {0}   # login shell so `conda activate` works


jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Verify required files
        run: |
          set -euo pipefail
          test -f config/emseq-conda-env.yaml
          test -f workflows/test.smk
          test -f config/test.yaml

      - name: Create/Update env (mamba, then conda fallback)
        run: |
          set -euo pipefail
          if conda env list | awk '{print $1}' | grep -qx emseq; then
            echo "Updating existing env 'emseq'..."
            mamba env update -n emseq -f config/emseq-conda-env.yaml -vv || \
              conda env update -n emseq -f config/emseq-conda-env.yaml -vv
          else
            echo "Creating env 'emseq'..."
            mamba env create -n emseq -f config/emseq-conda-env.yaml -vv || \
              conda env create -n emseq -f config/emseq-conda-env.yaml -vv
          fi
          conda env list
          conda run -n emseq python -V || true
          conda run -n emseq samtools --version || true

      - name: Snakemake dry-run
        run: |
          set -euo pipefail
          conda activate emseq
          snakemake \
            -s workflows/test.smk \
            --configfile config/test.yaml \
            --cores 4 \
            --dry-run \
            --printshellcmds \
            --rerun-incomplete \
            --resources concurrency=50

      - name: Summary
        if: ${{ success() || failure() }}
        run: |
          conda activate emseq
          snakemake -s workflows/test.smk --summary --cores 1 --dry-run
