name: test-data

on:
  pull_request:
    paths:
      - "tools/get_test_data.sh"
      - "tests/**"
      - ".github/workflows/test-data.yml"
  schedule:
    - cron: "0 4 * * 1"   # Mondays 04:00 UTC
  workflow_dispatch: {}

concurrency:
  group: test-data-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    name: Run get_test_data.sh and verify outputs
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      # Build the same env you use locally (adjust path if needed)
      - name: Setup Conda (Mambaforge) with repo env
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          auto-activate-base: false
          use-mamba: true
          activate-environment: emseq
          environment-file: config/emseq-conda-env.yaml

      # Optional: cache generated fixtures to speed reruns
      - name: Cache test data (optional)
        id: cache-testdata
        uses: actions/cache@v4
        with:
          path: tests/full
          key: testdata-${{ hashFiles('tools/get_test_data.sh') }}

      - name: Make script executable
        run: chmod +x tools/get_test_data.sh

      # NOTE: shell: bash -l logs into the conda-enabled shell so env is active
      - name: Execute script
        shell: bash -l {0}
        run: ./tools/get_test_data.sh

      - name: Sanity checks
        shell: bash -l {0}
        run: |
          set -euo pipefail
          test -d tests/full || (echo "tests/full not created" >&2; exit 1)

          fq_count=$(find tests/full -type f -name "*fastq.gz" | wc -l)
          (( fq_count >= 4 )) || { echo "Expected ≥4 FASTQs, got ${fq_count}"; exit 1; }

          fasta_count=$(find tests/full \
            -type f \( -name "*chr22*.fa*" -o -name "*lambda*.fa*" -o -name "*pUC19*.fa*" \) | wc -l)
          (( fasta_count >= 1 )) || { echo "Expected ≥1 reference FASTA"; exit 1; }

          echo "OK: test data present."
