name: test-data

on:
  pull_request:
    paths:
      - "tools/get_test_data.sh"
      - "tests/**"
      - ".github/workflows/test-data.yml"
      - "config/emseq-conda-env.yaml"
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch: {}

concurrency:
  group: test-data-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    name: Run get_test_data.sh and verify outputs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      # Prove the file is where we think it is (fail early if not).
      - name: Verify env file exists
        run: |
          set -euo pipefail
          ls -lah
          ls -lah config || true
          test -f config/emseq-conda-env.yaml || { echo "Missing: config/emseq-conda-env.yaml"; exit 1; }
          sed -n '1,60p' config/emseq-conda-env.yaml

      # Build env from your YAML (fast + cached)
      - name: Setup micromamba from repo env
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: config/emseq-conda-env.yaml
          environment-name: emseq
          cache-environment: true
          cache-downloads: true
          condarc: |
            channel_priority: strict
            channels:
              - conda-forge
              - bioconda

      # Optional cache for generated fixtures
      - name: Cache test data (optional)
        id: cache-testdata
        uses: actions/cache@v4
        with:
          path: tests/full
          key: testdata-${{ hashFiles('tools/get_test_data.sh') }}

      - name: Make script executable
        run: chmod +x tools/get_test_data.sh

      - name: Execute script
        run: micromamba run -n emseq ./tools/get_test_data.sh

      - name: Sanity checks
        run: |
          set -euo pipefail
          test -d tests/full || (echo "tests/full not created" >&2; exit 1)

          fq_count=$(find tests/full -type f -name "*fastq.gz" | wc -l)
          (( fq_count >= 4 )) || { echo "Expected ≥4 FASTQs, got ${fq_count}"; exit 1; }

          fasta_count=$(find tests/full \
            -type f \( -name "*chr22*.fa*" -o -name "*lambda*.fa*" -o -name "*pUC19*.fa*" \) | wc -l)
          (( fasta_count >= 1 )) || { echo "Expected ≥1 reference FASTA"; exit 1; }

          echo "OK: test data present."
