name: test-data

on:
  pull_request:
    paths:
      - "tools/get_test_data.sh"
      - "tests/**"
      - "config/emseq-conda-env.yaml"
      - ".github/workflows/test-data.yml"
  schedule:
    - cron: "0 4 * * 1"   # Mondays 04:00 UTC
  workflow_dispatch: {}

concurrency:
  group: test-data-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    name: Run get_test_data.sh and verify outputs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      # Fail fast if the env file isn't where we expect
      - name: Verify env file exists
        run: |
          set -euo pipefail
          test -f config/emseq-conda-env.yaml || { echo "Missing: config/emseq-conda-env.yaml"; exit 1; }
          sed -n '1,30p' config/emseq-conda-env.yaml

      # Build env from your YAML (uses name: in the file; no activate-environment)
      - name: Setup Conda (Miniforge) from repo env
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          auto-activate-base: false
          use-mamba: true
          environment-file: config/emseq-conda-env.yaml

      # Optional cache for generated fixtures
      - name: Cache test data (optional)
        id: cache-testdata
        uses: actions/cache@v4
        with:
          path: tests/full
          key: testdata-${{ hashFiles('tools/get_test_data.sh') }}

      - name: Make script executable
        run: chmod +x tools/get_test_data.sh

      # Use login shell so the Conda env is active (puts conda on PATH)
      - name: Execute script
        shell: bash -l {0}
        run: ./tools/get_test_data.sh

      - name: Sanity checks
        shell: bash -l {0}
        run: |
          set -euo pipefail
          test -d tests/full || (echo "tests/full not created" >&2; exit 1)

          fq_count=$(find tests/full -type f -name "*fastq.gz" | wc -l)
          (( fq_count >= 4 )) || { echo "Expected ≥4 FASTQs, got ${fq_count}"; exit 1; }

          fasta_count=$(find tests/full \
            -type f \( -name "*chr22*.fa*" -o -name "*lambda*.fa*" -o -name "*pUC19*.fa*" \) | wc -l)
          (( fasta_count >= 1 )) || { echo "Expected ≥1 reference FASTA"; exit 1; }

          echo "OK: test data present."
